// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.TextReadabilityScore
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("textCounts")]
        public TextCounts TextCounts { get; set; }

        [JsonProperty("readability")]
        public Readability Readability { get; set; }

        [JsonProperty("readabilityText")]
        public ReadabilityText ReadabilityText { get; set; }

        [JsonProperty("averageGradeLevel")]
        public double? AverageGradeLevel { get; set; }

        [JsonProperty("targetAudience")]
        public string TargetAudience { get; set; }
    }

    public partial class Readability
    {
        [JsonProperty("fleschReadingEase")]
        public double? FleschReadingEase { get; set; }

        [JsonProperty("fleschKincaidGrade")]
        public double? FleschKincaidGrade { get; set; }

        [JsonProperty("gunningFog")]
        public double? GunningFog { get; set; }

        [JsonProperty("colemanLiauIndex")]
        public double? ColemanLiauIndex { get; set; }

        [JsonProperty("smogIndex")]
        public double? SmogIndex { get; set; }

        [JsonProperty("automatedReadabilityIndex")]
        public double? AutomatedReadabilityIndex { get; set; }

        [JsonProperty("daleChallReadabilityScore")]
        public long? DaleChallReadabilityScore { get; set; }
    }

    public partial class ReadabilityText
    {
        [JsonProperty("fleschReadingEase")]
        public string FleschReadingEase { get; set; }

        [JsonProperty("daleChallReadabilityScore")]
        public string DaleChallReadabilityScore { get; set; }
    }

    public partial class TextCounts
    {
        [JsonProperty("syllableCount")]
        public long? SyllableCount { get; set; }

        [JsonProperty("lexiconCount")]
        public long? LexiconCount { get; set; }

        [JsonProperty("sentenceCount")]
        public long? SentenceCount { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
